favicon: /favicon.ico


# Nav Menus
menu:
    Index: /
    Archives: /archives

# Nav Shortcut Icons
nav_icons:
    - ['/images/github.svg', 'https://github.com/ChengUU']
    - ['/images/rss.svg', '/atom.xml']

# Friend Links
friend_links:
    - ['AngryPowman', 'This is a link', 'http://powman.org']
    - ['Demo Links', 'You can change this in your theme config', 'http://powman.org']


# About
about_info:
    name: "ChengXX"
    bio: "富贵必从勤苦得，男儿须读五车书"
    avatar: "/images/avatar.png"

# Comment
# e.g disqus: seansun
disqus:
  enable: true
  shortname: chenguu #your name
  count: true
duoshuo: 

# Analytics
google_analytics: 
tencent_analytics: 66115146
 
# Copyright Infomation
startyear: 2017
